### ISSUE TITLE
SessionStateAsyncExample throws exception

### ISSUE THREAD

**Issue by bcubedb3** [couchbaselabs/couchbase-aspnet#78]
The example does not have any code to add anything to the session state. When i added  Session["mytest"] = "Tester";  to the HomeController Index method, it throws an exception 
Object reference not set to an instance of an object. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
Source Error: 
 Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Line 151:            var item = get.Value; Line 152: Line 153:            if (get.Success && item != null && (uint) lockId == item.LockId) Line 154:            { Line 155:                item.Locked = false;
Source File:  C:\Users\bbonner\Source\Repos\couchbase-aspnet2.0\src\Couchbase.AspNet\Session\CouchbaseSessionStateProviderAsync.cs    Line:  153 

Stack Trace: 

[NullReferenceException: Object reference not set to an instance of an object.]
   Couchbase.AspNet.Session.<ReleaseItemExclusiveAsync>d__36.MoveNext() in C:\Users\bbonner\Source\Repos\couchbase-aspnet2.0\src\Couchbase.AspNet\Session\CouchbaseSessionStateProviderAsync.cs:153
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Runtime.CompilerServices.ConfiguredTaskAwaiter.GetResult() +26
   Couchbase.AspNet.Session.<SetAndReleaseItemExclusiveAsync>d__39.MoveNext() in C:\Users\bbonner\Source\Repos\couchbase-aspnet2.0\src\Couchbase.AspNet\Session\CouchbaseSessionStateProviderAsync.cs:220
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.AspNet.SessionState.<ReleaseStateAsyncImpl>d__80.MoveNext() +782
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.AspNet.SessionState.TaskAsyncHelper.EndTask(IAsyncResult ar) +63
   Microsoft.AspNet.SessionState.SessionStateModuleAsync.EndOnReleaseState(IAsyncResult result) +6
   System.Web.AsyncEventExecutionStep.InvokeEndHandler(IAsyncResult ar) +156
   System.Web.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar) +9775168

**Comment by jeffrymorris** [comment]
Hi @bcubedb3 -

Thanks for reporting, I'll look into this ASAP.

-Jeff

**Comment by jeffrymorris** [comment]
Hi @bcubedb3 -

I was able to replicate and its definitely a bug. I'll push a patch in the next couple of days.

Thanks for reporting,

Jeff

**Comment by jeffrymorris** [comment]
Should be fixed with this commit: https://github.com/couchbaselabs/couchbase-aspnet/commit/d39500d9982f8b8d862da2a16b95ec7e0d9a3e58
